import { Metadata } from 'next';
import type { Locale } from './i18n-routing';

/**
 * 多语言元数据配置
 * 为每种语言提供独立的 SEO 元数据
 */

const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://creatikit.asia';

// 英文元数据（默认语言，用于 Google 等国际搜索引擎）
const enMetadata: Metadata = {
  title: {
    default: 'CreatiKit.io - Free Online Creative Toolkit | 25+ Useful Tools, Image Compression, 3D Preview, Design Tools',
    template: '%s | CreatiKit.io',
  },
  description: 'CreatiKit.io provides 25+ free online creative tools: image compression, background removal, 3D model preview, pixel art generator, QR code generator, color palette, Markdown editor, whiteboard, SVG editor, CSS animator, audio visualizer, particle editor, physics & chemistry lab, and more. No registration required, completely free, all processing done locally in your browser to protect your privacy.',
  keywords: [
    'online tools',
    'free online tools',
    'image compression',
    'image compress',
    'JPG compress',
    'PNG compress',
    'image processing',
    'image editing',
    'background removal',
    'remove background',
    'transparent background',
    '3D preview',
    '3D model viewer',
    'GLB viewer',
    'GLTF viewer',
    'pixel art',
    'pixel art generator',
    'image to pixel',
    '8bit art',
    'QR code generator',
    'QR code maker',
    'color palette',
    'color picker',
    'color scheme',
    'Markdown editor',
    'online Markdown',
    'Markdown preview',
    'whiteboard',
    'drawing tool',
    'canvas tool',
    'GIF tool',
    'GIF splitter',
    'GIF combiner',
    'text analyzer',
    'SEO analyzer',
    'keyword density',
    'timestamp converter',
    'Unix timestamp',
    'hash calculator',
    'MD5 calculator',
    'SHA calculator',
    'physics lab',
    'physics simulation',
    'chemistry lab',
    'chemistry experiment',
    'virtual lab',
    'ecosystem sandbox',
    'online piano',
    'digital piano',
    'data visualization',
    'chart generator',
    'CSV to chart',
    'emoji collection',
    'emoji library',
    'creative tools',
    'design tools',
    'frontend tools',
    'SVG editor',
    'SVG editor tool',
    'CSS animation',
    'CSS animator',
    'animation maker',
    'audio visualizer',
    'spectrum analyzer',
    'audio waveform',
    'particle effects',
    'particle editor',
    'particle system',
    'gesture drawing',
    'gesture control',
    'weather tool',
    'weather forecast',
  ],
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: `${baseUrl}/en`,
    siteName: 'CreatiKit.io',
    title: 'CreatiKit.io - Free Online Creative Toolkit | 25+ Useful Tools',
    description: 'Provides 25+ free online creative tools: image compression, background removal, 3D preview, pixel art, QR code generator, SVG editor, CSS animation, audio visualizer, particle effects, and more. No registration required, completely free.',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'CreatiKit.io - Free Online Creative Toolkit, 25+ Useful Tools',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'CreatiKit.io - Free Online Creative Toolkit | 25+ Useful Tools',
    description: 'Provides 25+ free online creative tools: image compression, background removal, 3D preview, pixel art, QR code generator, SVG editor, CSS animation, audio visualizer, and more. No registration required, completely free.',
    images: ['/og-image.png'],
    creator: '@creatikit',
  },
};

// 中文元数据（用于百度等国内搜索引擎）
const zhMetadata: Metadata = {
  title: {
    default: 'CreatiKit.io - 免费在线创意工具箱 | 25+实用工具，图片压缩、3D预览、设计工具',
    template: '%s | CreatiKit.io',
  },
  description: 'CreatiKit.io 提供25+免费在线创意工具：图片压缩、背景移除、3D模型预览、像素艺术生成、二维码生成、调色板、Markdown编辑器、白板工具、SVG编辑器、CSS动画生成器、音频可视化、粒子编辑器、物理化学实验室等。无需注册，完全免费，所有处理在浏览器本地完成，保护您的隐私安全。',
  keywords: [
    '在线工具',
    '免费在线工具',
    '图片压缩',
    '图片压缩工具',
    'JPG压缩',
    'PNG压缩',
    '图片处理',
    '图片编辑',
    '背景移除',
    '去背景工具',
    '透明背景',
    '抠图工具',
    '3D预览',
    '3D模型查看器',
    'GLB预览',
    'GLTF预览',
    '像素艺术',
    '像素艺术生成器',
    '图片转像素',
    '8bit艺术',
    '二维码生成',
    'QR码生成',
    '二维码制作',
    '调色板',
    '配色工具',
    '颜色选择器',
    '取色器',
    'Markdown编辑器',
    '在线Markdown',
    'Markdown预览',
    '在线白板',
    '绘图工具',
    '画板工具',
    'GIF工具',
    'GIF分解',
    'GIF合成',
    '动图制作',
    '文本分析',
    'SEO分析工具',
    '关键词密度',
    '时间戳转换',
    'Unix时间戳',
    '哈希计算',
    'MD5计算',
    'SHA计算',
    '物理实验室',
    '物理模拟',
    '力学实验',
    '化学实验室',
    '化学实验',
    '虚拟实验',
    '生物沙盒',
    '生态系统模拟',
    '在线钢琴',
    '电子钢琴',
    '数据可视化',
    '图表生成',
    'CSV转图表',
    '表情符号',
    'Emoji大全',
    '在线工具箱',
    '创意工具',
    '设计工具',
    '前端工具',
    'SVG编辑器',
    'SVG编辑工具',
    'CSS动画',
    'CSS动画生成器',
    '动画制作工具',
    '音频可视化',
    '频谱分析',
    '音频波形',
    '粒子特效',
    '粒子编辑器',
    '粒子系统',
    '隔空写字',
    '手势控制',
    '天气预报',
    '天气查询',
  ],
  openGraph: {
    type: 'website',
    locale: 'zh_CN',
    url: `${baseUrl}/zh-CN`,
    siteName: 'CreatiKit.io',
    title: 'CreatiKit.io - 免费在线创意工具箱 | 25+实用工具',
    description: '提供25+免费在线创意工具：图片压缩、背景移除、3D预览、像素艺术、二维码生成、SVG编辑、CSS动画、音频可视化、粒子特效等。无需注册，完全免费，所有处理在浏览器本地完成，保护隐私安全。',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'CreatiKit.io - 免费在线创意工具箱，提供25+实用工具',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'CreatiKit.io - 免费在线创意工具箱 | 25+实用工具',
    description: '提供25+免费在线创意工具：图片压缩、背景移除、3D预览、像素艺术、二维码生成、SVG编辑、CSS动画、音频可视化等。无需注册，完全免费。',
    images: ['/og-image.png'],
    creator: '@creatikit',
  },
};

// 日文元数据
const jaMetadata: Metadata = {
  title: {
    default: 'CreatiKit.io - 無料オンラインクリエイティブツールキット | 25+便利なツール、画像圧縮、3Dプレビュー、デザインツール',
    template: '%s | CreatiKit.io',
  },
  description: 'CreatiKit.ioは25+の無料オンラインクリエイティブツールを提供：画像圧縮、背景除去、3Dモデルプレビュー、ピクセルアート生成、QRコード生成、カラーパレット、Markdownエディタ、ホワイトボード、SVGエディタ、CSSアニメーター、オーディオビジュアライザー、パーティクルエディタ、物理化学実験室など。登録不要、完全無料、すべての処理はブラウザでローカルに実行され、プライバシーを保護します。',
  keywords: [
    'オンラインツール',
    '無料オンラインツール',
    '画像圧縮',
    '画像圧縮ツール',
    'JPG圧縮',
    'PNG圧縮',
    '画像処理',
    '画像編集',
    '背景除去',
    '背景削除ツール',
    '透明背景',
    '3Dプレビュー',
    '3Dモデルビューア',
    'GLBビューア',
    'GLTFビューア',
    'ピクセルアート',
    'ピクセルアート生成器',
    '画像をピクセル化',
    '8bitアート',
    'QRコード生成',
    'QRコード作成',
    'カラーパレット',
    'カラーピッカー',
    '配色ツール',
    'Markdownエディタ',
    'オンラインMarkdown',
    'Markdownプレビュー',
    'ホワイトボード',
    '描画ツール',
    'キャンバスツール',
    'GIFツール',
    'GIF分割',
    'GIF結合',
    'テキスト分析',
    'SEO分析ツール',
    'キーワード密度',
    'タイムスタンプ変換',
    'Unixタイムスタンプ',
    'ハッシュ計算',
    'MD5計算',
    'SHA計算',
    '物理実験室',
    '物理シミュレーション',
    '化学実験室',
    '化学実験',
    '仮想実験',
    '生態系サンドボックス',
    'オンラインピアノ',
    'デジタルピアノ',
    'データ可視化',
    'チャート生成',
    'CSVからチャート',
    '絵文字コレクション',
    '絵文字ライブラリ',
    'クリエイティブツール',
    'デザインツール',
    'フロントエンドツール',
    'SVGエディタ',
    'SVG編集ツール',
    'CSSアニメーション',
    'CSSアニメーター',
    'アニメーション作成',
    'オーディオビジュアライザー',
    'スペクトラムアナライザー',
    'オーディオ波形',
    'パーティクルエフェクト',
    'パーティクルエディタ',
    'パーティクルシステム',
    'ジェスチャー描画',
    'ジェスチャー制御',
    '天気ツール',
    '天気予報',
  ],
  openGraph: {
    type: 'website',
    locale: 'ja_JP',
    url: `${baseUrl}/ja-JP`,
    siteName: 'CreatiKit.io',
    title: 'CreatiKit.io - 無料オンラインクリエイティブツールキット | 25+便利なツール',
    description: '25+の無料オンラインクリエイティブツールを提供：画像圧縮、背景除去、3Dプレビュー、ピクセルアート、QRコード生成、SVG編集、CSSアニメーション、オーディオビジュアライザー、パーティクルエフェクトなど。登録不要、完全無料。',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'CreatiKit.io - 無料オンラインクリエイティブツールキット、25+便利なツール',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'CreatiKit.io - 無料オンラインクリエイティブツールキット | 25+便利なツール',
    description: '25+の無料オンラインクリエイティブツールを提供：画像圧縮、背景除去、3Dプレビュー、ピクセルアート、QRコード生成、SVG編集、CSSアニメーション、オーディオビジュアライザーなど。登録不要、完全無料。',
    images: ['/og-image.png'],
    creator: '@creatikit',
  },
};

// 韩文元数据
const koMetadata: Metadata = {
  title: {
    default: 'CreatiKit.io - 무료 온라인 크리에이티브 툴킷 | 25+ 유용한 도구, 이미지 압축, 3D 미리보기, 디자인 도구',
    template: '%s | CreatiKit.io',
  },
  description: 'CreatiKit.io는 25+ 무료 온라인 크리에이티브 도구를 제공합니다: 이미지 압축, 배경 제거, 3D 모델 미리보기, 픽셀 아트 생성기, QR 코드 생성기, 색상 팔레트, Markdown 에디터, 화이트보드, SVG 에디터, CSS 애니메이터, 오디오 비주얼라이저, 파티클 에디터, 물리 화학 실험실 등. 등록 불필요, 완전 무료, 모든 처리는 브라우저에서 로컬로 완료되어 개인정보를 보호합니다.',
  keywords: [
    '온라인 도구',
    '무료 온라인 도구',
    '이미지 압축',
    '이미지 압축 도구',
    'JPG 압축',
    'PNG 압축',
    '이미지 처리',
    '이미지 편집',
    '배경 제거',
    '배경 제거 도구',
    '투명 배경',
    '3D 미리보기',
    '3D 모델 뷰어',
    'GLB 뷰어',
    'GLTF 뷰어',
    '픽셀 아트',
    '픽셀 아트 생성기',
    '이미지를 픽셀로',
    '8bit 아트',
    'QR 코드 생성',
    'QR 코드 만들기',
    '색상 팔레트',
    '색상 선택기',
    '색상 도구',
    'Markdown 에디터',
    '온라인 Markdown',
    'Markdown 미리보기',
    '화이트보드',
    '그리기 도구',
    '캔버스 도구',
    'GIF 도구',
    'GIF 분할',
    'GIF 결합',
    '텍스트 분석',
    'SEO 분석 도구',
    '키워드 밀도',
    '타임스탬프 변환',
    'Unix 타임스탬프',
    '해시 계산',
    'MD5 계산',
    'SHA 계산',
    '물리 실험실',
    '물리 시뮬레이션',
    '화학 실험실',
    '화학 실험',
    '가상 실험',
    '생태계 샌드박스',
    '온라인 피아노',
    '디지털 피아노',
    '데이터 시각화',
    '차트 생성',
    'CSV를 차트로',
    '이모지 컬렉션',
    '이모지 라이브러리',
    '크리에이티브 도구',
    '디자인 도구',
    '프론트엔드 도구',
    'SVG 에디터',
    'SVG 편집 도구',
    'CSS 애니메이션',
    'CSS 애니메이터',
    '애니메이션 제작',
    '오디오 비주얼라이저',
    '스펙트럼 분석기',
    '오디오 파형',
    '파티클 효과',
    '파티클 에디터',
    '파티클 시스템',
    '제스처 그리기',
    '제스처 제어',
    '날씨 도구',
    '날씨 예보',
  ],
  openGraph: {
    type: 'website',
    locale: 'ko_KR',
    url: `${baseUrl}/ko-KR`,
    siteName: 'CreatiKit.io',
    title: 'CreatiKit.io - 무료 온라인 크리에이티브 툴킷 | 25+ 유용한 도구',
    description: '25+ 무료 온라인 크리에이티브 도구를 제공합니다: 이미지 압축, 배경 제거, 3D 미리보기, 픽셀 아트, QR 코드 생성, SVG 편집, CSS 애니메이션, 오디오 비주얼라이저, 파티클 효과 등. 등록 불필요, 완전 무료.',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'CreatiKit.io - 무료 온라인 크리에이티브 툴킷, 25+ 유용한 도구',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'CreatiKit.io - 무료 온라인 크리에이티브 툴킷 | 25+ 유용한 도구',
    description: '25+ 무료 온라인 크리에이티브 도구를 제공합니다: 이미지 압축, 배경 제거, 3D 미리보기, 픽셀 아트, QR 코드 생성, SVG 편집, CSS 애니메이션, 오디오 비주얼라이저 등. 등록 불필요, 완전 무료.',
    images: ['/og-image.png'],
    creator: '@creatikit',
  },
};

/**
 * 根据语言获取元数据
 */
export function getMetadataForLocale(locale: Locale): Metadata {
  switch (locale) {
    case 'zh-CN':
      return zhMetadata;
    case 'ja-JP':
      return jaMetadata;
    case 'ko-KR':
      return koMetadata;
    case 'en':
    default:
      return enMetadata;
  }
}

/**
 * 获取默认元数据（英文，用于 x-default）
 */
export function getDefaultMetadata(): Metadata {
  return enMetadata;
}

